# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_videoinfo.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VideoInfoDialog(object):
    def setupUi(self, VideoInfoDialog):
        VideoInfoDialog.setObjectName("VideoInfoDialog")
        VideoInfoDialog.resize(420, 260)
        VideoInfoDialog.setMinimumSize(QtCore.QSize(420, 260))
        VideoInfoDialog.setMaximumSize(QtCore.QSize(420, 260))
        self.gridLayout = QtWidgets.QGridLayout(VideoInfoDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(VideoInfoDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pathLabel = QtWidgets.QLabel(self.frame)
        self.pathLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.pathLabel.setMaximumSize(QtCore.QSize(60, 30))
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout_2.addWidget(self.pathLabel, 0, 0, 1, 1)
        self.pathLineEdit = QtWidgets.QLineEdit(self.frame)
        self.pathLineEdit.setEnabled(True)
        self.pathLineEdit.setMinimumSize(QtCore.QSize(200, 24))
        self.pathLineEdit.setMaximumSize(QtCore.QSize(200, 24))
        self.pathLineEdit.setInputMask("")
        self.pathLineEdit.setReadOnly(False)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.gridLayout_2.addWidget(self.pathLineEdit, 0, 1, 1, 1)
        self.pathSelectButton = QtWidgets.QPushButton(self.frame)
        self.pathSelectButton.setMinimumSize(QtCore.QSize(80, 30))
        self.pathSelectButton.setMaximumSize(QtCore.QSize(80, 30))
        self.pathSelectButton.setAutoDefault(False)
        self.pathSelectButton.setObjectName("pathSelectButton")
        self.gridLayout_2.addWidget(self.pathSelectButton, 0, 2, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.frame)
        self.nameLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.nameLabel.setMaximumSize(QtCore.QSize(60, 30))
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(200, 24))
        self.nameLineEdit.setMaximumSize(QtCore.QSize(200, 24))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout_2.addWidget(self.nameLineEdit, 1, 1, 1, 1)
        self.startLabel = QtWidgets.QLabel(self.frame)
        self.startLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.startLabel.setMaximumSize(QtCore.QSize(60, 30))
        self.startLabel.setObjectName("startLabel")
        self.gridLayout_2.addWidget(self.startLabel, 2, 0, 1, 1)
        self.startTimeEdit = QtWidgets.QTimeEdit(self.frame)
        self.startTimeEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.startTimeEdit.setMaximumSize(QtCore.QSize(100, 30))
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.gridLayout_2.addWidget(self.startTimeEdit, 2, 1, 1, 1)
        self.endLabel = QtWidgets.QLabel(self.frame)
        self.endLabel.setMinimumSize(QtCore.QSize(60, 30))
        self.endLabel.setMaximumSize(QtCore.QSize(60, 30))
        self.endLabel.setObjectName("endLabel")
        self.gridLayout_2.addWidget(self.endLabel, 3, 0, 1, 1)
        self.endTimeEdit = QtWidgets.QTimeEdit(self.frame)
        self.endTimeEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.endTimeEdit.setMaximumSize(QtCore.QSize(100, 30))
        self.endTimeEdit.setObjectName("endTimeEdit")
        self.gridLayout_2.addWidget(self.endTimeEdit, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(209, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(VideoInfoDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(80, 30))
        self.cancelButton.setMaximumSize(QtCore.QSize(80, 30))
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 1, 1, 1)
        self.okButton = QtWidgets.QPushButton(VideoInfoDialog)
        self.okButton.setMinimumSize(QtCore.QSize(80, 30))
        self.okButton.setMaximumSize(QtCore.QSize(80, 30))
        self.okButton.setAutoDefault(False)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 1, 2, 1, 1)

        self.retranslateUi(VideoInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(VideoInfoDialog)

    def retranslateUi(self, VideoInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        VideoInfoDialog.setWindowTitle(_translate("VideoInfoDialog", "Video Info"))
        self.pathLabel.setText(_translate("VideoInfoDialog", "Path:"))
        self.pathSelectButton.setText(_translate("VideoInfoDialog", "Select"))
        self.nameLabel.setText(_translate("VideoInfoDialog", "Name:"))
        self.startLabel.setText(_translate("VideoInfoDialog", "Start:"))
        self.startTimeEdit.setDisplayFormat(_translate("VideoInfoDialog", "hh:mm:ss"))
        self.endLabel.setText(_translate("VideoInfoDialog", "End:"))
        self.endTimeEdit.setDisplayFormat(_translate("VideoInfoDialog", "hh:mm:ss"))
        self.cancelButton.setText(_translate("VideoInfoDialog", "Cancel"))
        self.okButton.setText(_translate("VideoInfoDialog", "Ok"))

